server:
  port: 8081

spring:
  application:
    name: im-user-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Zhuyinghua123..
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.im.user.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  charset:
    console: UTF-8
    file: UTF-8
