# im-square-service 开发环境配置

im:
  datasource:
    username: root
    password: Zhuyinghua123..
  redis:
    password: 123456
  jwt:
    secret: im-chat-secret-key-2024
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDZjKwXoPduSX4RfuyT
    access-key-secret: SmXn71oOz6t0QRikCNGxGS1nRKNWa4
    bucket-name: im-chat-zyh

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/im_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

# content-review:
#   enabled: false
#   api-url: ""
#   api-key: ""
#   timeout-ms: 3000
