server:
  port: 8085

spring:
  application:
    name: im-square-service
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${im.datasource.username}
    password: ${im.datasource.password}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

  data:
    redis:
      host: localhost
      port: 6379
      password: ${im.redis.password}
      database: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.im.square.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: WARN
    com.im.square: INFO
    org.springframework.web: WARN
    org.mybatis: WARN
    com.alibaba.druid: WARN
  charset:
    console: UTF-8
    file: UTF-8
